DROP TABLE IF EXISTS chat;

CREATE TABLE chat (
      id SERIAL PRIMARY KEY,
      sender_id INT NOT NULL REFERENCES userInfo(id),
      message VARCHAR(255)  NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
  );