DROP TABLE IF EXISTS resetCode;

CREATE TABLE resetCode
(
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL REFERENCES userInfo(email) ON DELETE CASCADE,
    code VARCHAR(255)  NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);